# Generated by Django 6.1 on 2026-08-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature_c', models.FloatField()),
                ('battery_pct', models.FloatField()),
                ('power_draw_w', models.FloatField()),
                ('orientation_pitch', models.FloatField()),
                ('orientation_roll', models.FloatField()),
                ('orientation_yaw', models.FloatField()),
                ('comms_signal_pct', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_type', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
